# source 'https://github.com/CocoaPods/Specs.git'
$iOSVersion = '15.5'
platform :ios, $iOSVersion
# Pod::PICKER_MEDIA = false, Pod::PICKER_AUDIO = false

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'


project 'Runner', {
  'Debug' => :debug,
  'Debug-SimulatorUI' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

# pod 'GoogleMLKit/LanguageID'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  simulator_ui_configuration = 'Debug-SimulatorUI'
  mlkit_frameworks = %w[
    MLImage
    MLKitBarcodeScanning
    MLKitCommon
    MLKitLanguageID
    MLKitNaturalLanguage
    MLKitVision
    google_mlkit_barcode_scanning
    google_mlkit_commons
    google_mlkit_language_id
  ]

  installer.pods_project.build_configurations.each do |config|
#       config.build_settings["EXCLUDED_ARCHS[sdk=*]"] = "armv7"
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] =
        config.name == simulator_ui_configuration ? "" : "arm64"
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = $iOSVersion
  end
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      xcconfig_path = config.base_configuration_reference.real_path
      xcconfig = File.read(xcconfig_path)
      xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
      File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }

#       config.build_settings["EXCLUDED_ARCHS[sdk=*]"] = "armv7"
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] =
        config.name == simulator_ui_configuration ? "" : "arm64"
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = $iOSVersion
      config.build_settings['SWIFT_VERSION'] = '5.0'  # required by simple_permission
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
      # You can enable the permissions needed here. For example to enable camera
      # permission, just remove the `#` character in front so it looks like this:
      #
      # ## dart: PermissionGroup.camera
      # 'PERMISSION_CAMERA=1'
      #
      #  Preprocessor definitions can be found in: https://github.com/Baseflow/flutter-permission-handler/blob/develop/permission_handler/ios/Classes/PermissionHandlerEnums.h
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',

        ## dart: PermissionGroup.calendar
        # 'PERMISSION_EVENTS=1',

        ## dart: PermissionGroup.reminders
        # 'PERMISSION_REMINDERS=1',

        ## dart: PermissionGroup.contacts
        # 'PERMISSION_CONTACTS=1',

        ## dart: PermissionGroup.camera
        # 'PERMISSION_CAMERA=1',

        ## dart: PermissionGroup.microphone
        # 'PERMISSION_MICROPHONE=1',

        ## dart: PermissionGroup.speech
        # 'PERMISSION_SPEECH_RECOGNIZER=1',

        ## dart: PermissionGroup.photos
        'PERMISSION_PHOTOS=1',

        ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
        # 'PERMISSION_LOCATION=1',

        ## dart: PermissionGroup.notification
        # 'PERMISSION_NOTIFICATIONS=1',

        ## dart: PermissionGroup.mediaLibrary
        # 'PERMISSION_MEDIA_LIBRARY=1',

        ## dart: PermissionGroup.sensors
        # 'PERMISSION_SENSORS=1',

        ## dart: PermissionGroup.bluetooth
        # 'PERMISSION_BLUETOOTH=1',

        ## dart: PermissionGroup.appTrackingTransparency
        # 'PERMISSION_APP_TRACKING_TRANSPARENCY=1'
      ]
      if config.name == simulator_ui_configuration
        definitions = config.build_settings['GCC_PREPROCESSOR_DEFINITIONS']
        if definitions.is_a?(Array)
          definitions << 'EROS_SIMULATOR_UI_TEST=1'
        else
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = [
            definitions,
            'EROS_SIMULATOR_UI_TEST=1',
          ].compact
        end
      end
    end
  end

  installer.aggregate_targets.each do |aggregate_target|
    xcconfig = aggregate_target.build_settings(simulator_ui_configuration).xcconfig
    next unless xcconfig

    xcconfig.attributes['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = ''
    mlkit_frameworks.each do |framework_name|
      xcconfig.other_linker_flags[:frameworks].delete(framework_name)
    end
    xcconfig.save_as(aggregate_target.xcconfig_path(simulator_ui_configuration))
  end
end
